version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-bookmanager
    restart: always
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ../backend  # ✅ correct: relative to infra/
      dockerfile: Dockerfile
    container_name: bookmanager-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookdb
      SPRING_DATASOURCE_USERNAME: bookuser
      SPRING_DATASOURCE_PASSWORD: bookpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
